# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVXiyG87TaWNQzewQKxGdeU0Q4kctMsI
"""

import optuna

import os
from driver import Driver
path_to_data = './data/adani.csv'
params = {}
params['n_steps']       = 14
params['n_components']  = 3
params['val_split']     = 0.2
params['factor']        = 0.01
params['patience']      = 40
params['learning_rate'] = 0.001
params['min_delta']     = 0.1
params['epochs']        = 1
params['batch_size']    = 16
params['monitor_param'] = 'val_loss'

# driver = Driver(path_to_data = path_to_data, server_space='subdir', server_name='file', params=params)
# driver._drive()
# driver.monitored_param

# print(driver.monitored_param)

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    params = {}
    params['n_steps']       = trial.suggest_int('n_steps', 6,7)
    params['n_components']    = trial.suggest_int('n_components', 3,4)
    params['val_split']         = 0.2
    params['factor']            = trial.suggest_loguniform('factor', 1e-5, 1e-4)
    params['patience']          = trial.suggest_int('patience', 10,11)
    params['learning_rate']     = trial.suggest_loguniform('learning_rate', 1e-5, 1e-4)
    params['min_delta']         = trial.suggest_loguniform('min_delta', 1e-5, 1e-4)
    params['epochs']            = 1
    params['batch_size']        = 16
    params['monitor_param'] = 'val_loss'
    driver = Driver(path_to_data = path_to_data, server_space='subdir', server_name='file', params=params)
    driver._drive()

    return driver.monitored_param
    

study = optuna.create_study()
study.optimize(objective, n_trials=500)

study.best_params  # E.g. {'x': 2.002108042}



study.best_params

